openapi: 3.0.1
info:
  title: Zolve POC
  description: Zolve API.
  version: 1.0.0
servers:
  - url: /v2

paths:
  /add:
    post:
      summary: Add User
      operationId: addUser
      requestBody:
        description: User to be added to Zolve
        content:
          application/json:
            schema:
              type: object
              $ref: '#components/schemas/UserDto'
        required: true
      responses:
        200:
          description: User added
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/UserDto'

  /debit:
    post:
      summary: Debit money from Account
      operationId: debitAmount
      requestBody:
        description: Amount debited from Zolve user
        content:
          application/json:
            schema:
              type: object
              $ref: '#components/schemas/ReceiptDto'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ReceiptDto'
  /credit:
    post:
      summary: Credit money to Account
      operationId: creditAmount
      requestBody:
        description: Amount added to Zolve user
        content:
          application/json:
            schema:
              type: object
              $ref: '#components/schemas/ReceiptDto'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ReceiptDto'
  /send:
    post:
      summary: send money from payer to payee Account
      operationId: sendAmount
      requestBody:
        description: Amount added to Zolve user
        content:
          application/json:
            schema:
              type: object
              $ref: '#components/schemas/ReceiptDto'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ReceiptDto'

  /balance:
    get:
      summary: Show banace of User Account
      operationId: showBalance
      parameters:
        - name: userId
          in: path
          description: userId you are searching
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ReceiptDto'

  /history:
    get:
      summary: Show banace of User Account
      operationId: userHistory
      parameters:
        - name: userId
          in: path
          description: userId you are searching
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string



components:
  schemas:
    ReceiptDto:
      type: object
      properties:
        payer:
          type: integer
          format: int64
        benificiary:
          type: integer
          format: int64
        amount:
          type: number
          format: double

    UserDto:
      type: object
      properties:
        firstName:
          type: string
          example: "Puja"
        lastName:
          type: string
          example: "Burman"
        contact:
          type: string
          example: "9339226744"
        balance:
          type: number
          format: double

